### PR TITLE
CI test sanity

### PR DESCRIPTION
**Pull request by lostmsu**
Ensure new tests can be easily authored and are run by CI

### CODE REVIEW

**Comment by lostmsu** [comment]
@koubaa , can you review this one? It should unblock CI and local testing.

**Comment by koubaa** [comment]
@lostmsu I tried it and added the env vars to the top of the TestRuntimeConfig.Ensure() and got this error when trying to set PythonEngine.PythonHome:

System.TypeInitializationException: 'The type initializer for 'Delegates' threw an exception.'
FileLoadException: Could not load C:\Users\Admin\AppData\Local\Programs\Python\Python37\python37.dll

When debugging before the line where it sets PythonEngine.PythonHome I can't even get the initial value of PythonEngine.PythonHome.  To me it suggests a failure to load the Python runtime dll properly.  I guess this has to do with static initialization when the assembly first loads.

Next I tried setting the variable before launching VS and it passes.  So I suggest that you update the readme and remove the alternative instructions.

**Comment by lostmsu** [comment]
@koubaa can you check if Python architecture (e.g. x64 or x86) bitness matches .NET?

I just tried to add this to the beginning of `Ensure` with no environment variables set elsewhere, and it worked:

```csharp
Environment.SetEnvironmentVariable("PYTHON_HOME",
  @"C:\Program Files (x86)\Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64");
Environment.SetEnvironmentVariable("PYTHON_VERSION", "3.7");
```

I also set Test -> Processor Architecture for AnyCPU projects -> x64.

**Comment by lostmsu** [comment]
@koubaa creating a file with the following content also worked:

```csharp
namespace Python.Runtime.Codecs
{
    using System;

    partial class TestsRuntimeConfig
    {
        static TestsRuntimeConfig()
        {
            Environment.SetEnvironmentVariable("PYTHON_HOME",
                @"C:\Program Files (x86)\Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\Python\Miniconda\Miniconda3-x64");
            Environment.SetEnvironmentVariable("PYTHON_VERSION", "3.7");
        }
    }
}
```

**Comment by koubaa** [comment]
@lostmsu my architectures do match.

**Comment by lostmsu** [comment]
@koubaa do you actually have Python installed in C:\Users\Admin\AppData\Local\Programs\Python\Python37 ?

**Comment by koubaa** [comment]
image
@lostmsu

**Comment by koubaa** [comment]
@lostmsu on this branch, this worked for me.  Earlier I had merged your changes and tried it in my branch.  let me try to see what happened there.

**Comment by koubaa** [comment]
@lostmsu I can no longer reproduce the error (I should have pushed a branch when I had the issue).  sorry for the trouble.

**Comment by lostmsu** [comment]
@koubaa should I merge?

**Comment by koubaa** [comment]
@lostmsu yes please go ahead

**Review by koubaa — APPROVED** [review]

**Pull request merged**
